### ISSUE TITLE
Elasticsearch 2.0 doesn't support dot in the field name

### ISSUE THREAD

**Issue by msimos** [looplab/logspout-logstash#11]
Elasticsearch 2.0 doesn't support dot in the field name:

https://www.elastic.co/guide/en/elasticsearch/reference/current/_mapping_changes.html#_field_names_may_not_contain_dots

In logstash.go it has:

```
type LogstashMessage struct {
    Message  string `json:"message"`
    Name     string `json:"docker.name"`
    ID       string `json:"docker.id"`
    Image    string `json:"docker.image"`
    Hostname string `json:"docker.hostname"`
}
```

This will cause an issue either upgrading to or using Elasticsearch 2.0. I suggest renaming the dots with an underscore or using nested fields.

**Comment by maxekman** [comment]
Thanks for the feedback. Unfortunately I currently don't use logspout, but I will gladly accept a PR with the changes.

**Comment by wkruse** [comment]
As a quickfix the fields can be renamed in Logstash filter.

``` bash
filter {
  mutate {
    rename => { "docker.id" => "container_id" }
    rename => { "docker.name" => "container_name" }
    rename => { "docker.image" => "docker_image" }
    rename => { "docker.hostname" => "docker_hostname" }
  }
}
```

**Comment by srhopkins** [comment]
@maxekman you mentioned not using logspout; what are you using currently?

**Comment by maxekman** [comment]
@srhopkins I use a minimal Go service that forwards raw logs (which are already in JSON) directly from the Docker socket to ES.
