### ISSUE TITLE
cannot make it work

### ISSUE THREAD

**Issue by mogadanez** [looplab/logspout-logstash#14]
run with 

```
docker run -d \
--restart=always \
--volume=/var/run/docker.sock:/tmp/docker.sock \
-e "ROUTE_URIS=logstash://host:5505" \
my-docker-registry/logspout-logstash:latest
```

it starts, but nothing goes to logstash
docker logs report 

```
# logspout v3-master-custom by gliderlabs
# adapters: logstash raw tcp syslog
# options : persist:/mnt/routes
# jobs    : pump http[routes]:80
# routes  :
#   ADAPTER     ADDRESS         CONTAINERS      SOURCES OPTIONS
#   logstash    host:5505                         map[]
```

how to diagnose cause?

**Comment by maxekman** [comment]
You can always try to run a UDP server and connect it to that, as a first step. The nc command can do that.

**Comment by mogadanez** [comment]
Yes, it works fine.
nc -vnzu host 5505
Connection to 10.0.0.119 5505 port [udp/*] succeeded!
and messages X appears in kibana

**Comment by mogadanez** [comment]
Looks like it's same as https://github.com/looplab/logspout-logstash/issues/7
