### ISSUE TITLE
LOGSTASH_TAGS doesn't work

### ISSUE THREAD

**Issue by mervynzhang** [looplab/logspout-logstash#33]
hi,

LOGSTASH_TAGS doesn't work. getopt only return logspout container's env. 

To get other containers' env, i think we need to use container.config.Env. But i'm new to logspout, could we do that?

**Comment by mervynzhang** [comment]
hello,

Maybe Container.Config.Labels is better since it's lighter than container.config.Env in the loop

`
for label, value := range m.Container.Config.Labels {
  if label == "LOGSTASH_TAGS"  {
    strTags = value
    break
  }
}
`

**Comment by maxekman** [comment]
Should be fixed by #31, closing this for now.
