### ISSUE TITLE
Question: What's the value-add of this adaptor?

### ISSUE THREAD

**Issue by johnharris85** [looplab/logspout-logstash#39]
Logspout can already send logs directly to Logstash right? What does this adaptor add to that functionality? 

(evaluating logging stacks atm)

**Comment by maxekman** [comment]
I think Logspout is pretty minimalistic and depends on adaptors, like this one. You could possibly use one of the simpler formats included with Logspout, but that has its limitations. Maybe I missed something?

**Comment by maxekman** [comment]
Closing due to no response.
