### ISSUE TITLE
don't see logstash.go

### ISSUE THREAD

**Issue by suchisubhra** [looplab/logspout-logstash#40]
I followed the instruction and build the docker.
I run the docker  and login to  to  docker.

I checked /erc dir..I see modules.go has my  content ...I didn't find logstash.go 
also under adapter dir  I don't see logstash.

Am I missing anything?

**Comment by suchisubhra** [comment]
please close this issue..I got my answer.. You guys are deleting /go

**Comment by maxekman** [comment]
Ok, thanks. Good you got it solved. :)
