### ISSUE TITLE
Is there a way collecting multiline logs as a single event to logstash? 

### ISSUE THREAD

**Issue by dengqingpei1990** [looplab/logspout-logstash#53]
Is this possible to collect multiline logs such as java stack trace as an event and send to logstash?

Logstash multiline module doc says that

> If you are using a Logstash input plugin that supports multiple hosts, such as the Beats input plugin input plugin, you should not use the multiline codec to handle multiline events. Doing so may result in the mixing of streams and corrupted event data. In this situation, you need to handle multiline events before sending the event data to Logstash.

So that I think that will be a wonderful thing if logspout can do this.

**Comment by StoyanIvanovI** [comment]
Not really. I banged my head against this wall for a couple of days. I would use (and currently am using) Filebeat with log mounting. Would be really great if there is an option to do newline checks inside logspout-logstash.

**Comment by bjitd** [comment]
@StoyanIvanovI  I'm using logspout to ship log to logstash. I'm wondering is their way I can ship log from inside container, I don't want to write to console , more of like each container has its own log file something like `xxx-app-spark.log` one of the options could be running file beat inside the container but that seems like over kill

**Comment by maxekman** [comment]
I will close this as it is more a question than an issue with the project.
