### ISSUE TITLE
TLS & Client Certs

### ISSUE THREAD

**Issue by setiseta** [looplab/logspout-logstash#59]
Is it possible to use it with TLS and to use a client cert?
Any hints how to setup this?
With slef signed certs.

**Comment by alekseyl1992** [comment]
any update on this?

**Comment by maxekman** [comment]
I haven’t used it with TLS, and currently I’m not using the project myself.

**Comment by setiseta** [comment]
me too, I've switched to filebeat.
you can collect dockerlogs with filebeats and send it to elastic search directly or to logstash.
