### ISSUE TITLE
Logstash restart breaks logs flow

### ISSUE THREAD

**Issue by PavelVanecek** [looplab/logspout-logstash#7]
Hi,

I have configured logstash and logspout to send logs from machine A to machine B. Everything works fine, but restarting logstash breaks the logs flow. All logs are still visible using http output and logspout stdout says `logstash: write udp: connection refused`. That's expected: logstash is booting up. Restarting the logspout container makes it send the logs again.

How can I make logspout reconnect without restart?

**Comment by tobowers** [comment]
We are having the same issue. Our solution was to modify the plugin to just die at connection error (and then have a custom logspout container that waits for the connection to be available in a bootstrap)

**Comment by sege** [comment]
We're having the same problem. Any good workaround out there? Watchdog solution, restart logspout if it happens?

**Comment by tobowers** [comment]
@sege this was our change: https://github.com/mdx-dev/logspout-logstash/blob/master/logstash.go#L58-L59

**Comment by jmreicha** [comment]
I'm seeing the write udp connection error as well except for me, it seems to be happening randomly.  Is there a good way to troubleshoot why it happens or pinpoint what exactly is causing the failures?

**Comment by maxekman** [comment]
I have changed the behavior to exit with code 1 on write failures, if this helps. See 6b2fe61.

**Comment by jmreicha** [comment]
I should have some time to test this today.

**Comment by jmreicha** [comment]
So it looks like the restart on non zero exit status is working.  However it is also restarting when it hits an oversized packet.  Here's what the log looks like:

`2016/06/23 17:11:30 logstash:write udp 172.17.0.9:36305->172.16.0.100:5001: write: message too long`

Is this expected?  I think everything is okay, the logspout containers just restart quite a bit.  I should be able to fine tune the logging a little bit but I thought it was at least worth mentioning.

**Comment by maxekman** [comment]
It is expected, as every error is treated equally for now. If you can come up with a strategy on how to handle too large messages a PR would be nice, but I think the subject is a bit tricky with UDP. Any thoughts?

**Comment by maxekman** [comment]
I'll close this for now as no solution has been suggested.
